module.exports = (req, res) => {
  res.setHeader('Access-Control-Allow-Origin', '*');
  const stocks = [
    {symbol:"NIFTY",name:"Nifty 50 Index",sector:"Index"},
    {symbol:"BANKNIFTY",name:"Bank Nifty Index",sector:"Index"},
    {symbol:"FINNIFTY",name:"Nifty Financial Services",sector:"Index"},
    {symbol:"MIDCPNIFTY",name:"Nifty Midcap Select",sector:"Index"},
    {symbol:"RELIANCE",name:"Reliance Industries",sector:"Energy"},
    {symbol:"TCS",name:"Tata Consultancy Services",sector:"IT"},
    {symbol:"HDFCBANK",name:"HDFC Bank",sector:"Banking"},
    {symbol:"INFY",name:"Infosys",sector:"IT"},
    {symbol:"ICICIBANK",name:"ICICI Bank",sector:"Banking"},
    {symbol:"HINDUNILVR",name:"Hindustan Unilever",sector:"FMCG"},
    {symbol:"BAJFINANCE",name:"Bajaj Finance",sector:"Finance"},
    {symbol:"WIPRO",name:"Wipro",sector:"IT"},
    {symbol:"SBIN",name:"State Bank of India",sector:"Banking"},
    {symbol:"AXISBANK",name:"Axis Bank",sector:"Banking"},
    {symbol:"MARUTI",name:"Maruti Suzuki",sector:"Auto"},
    {symbol:"TATAMOTORS",name:"Tata Motors",sector:"Auto"},
    {symbol:"SUNPHARMA",name:"Sun Pharmaceutical",sector:"Pharma"},
    {symbol:"NESTLEIND",name:"Nestle India",sector:"FMCG"},
    {symbol:"KOTAKBANK",name:"Kotak Mahindra Bank",sector:"Banking"},
    {symbol:"LT",name:"Larsen & Toubro",sector:"Infra"},
    {symbol:"HCLTECH",name:"HCL Technologies",sector:"IT"},
    {symbol:"TITAN",name:"Titan Company",sector:"Consumer"},
    {symbol:"ULTRACEMCO",name:"UltraTech Cement",sector:"Cement"},
    {symbol:"ADANIENT",name:"Adani Enterprises",sector:"Conglomerate"},
    {symbol:"BHARTIARTL",name:"Bharti Airtel",sector:"Telecom"},
    {symbol:"ITC",name:"ITC",sector:"FMCG"},
    {symbol:"NTPC",name:"NTPC",sector:"Utilities"},
    {symbol:"ONGC",name:"Oil & Natural Gas Corp",sector:"Energy"},
    {symbol:"DRREDDY",name:"Dr. Reddy Laboratories",sector:"Pharma"},
    {symbol:"CIPLA",name:"Cipla",sector:"Pharma"},
    {symbol:"DLF",name:"DLF",sector:"Real Estate"},
    {symbol:"ZOMATO",name:"Zomato",sector:"Internet"},
    {symbol:"DMART",name:"Avenue Supermarts",sector:"Retail"},
    {symbol:"IRCTC",name:"IRCTC",sector:"Travel"},
    {symbol:"TATAPOWER",name:"Tata Power",sector:"Utilities"},
    {symbol:"TATASTEEL",name:"Tata Steel",sector:"Metals"},
    {symbol:"HINDALCO",name:"Hindalco Industries",sector:"Metals"},
    {symbol:"VEDL",name:"Vedanta",sector:"Metals"},
    {symbol:"BAJAJ-AUTO",name:"Bajaj Auto",sector:"Auto"},
    {symbol:"EICHERMOT",name:"Eicher Motors",sector:"Auto"},
    {symbol:"HEROMOTOCO",name:"Hero MotoCorp",sector:"Auto"},
    {symbol:"ASIANPAINT",name:"Asian Paints",sector:"Consumer"},
    {symbol:"PIDILITIND",name:"Pidilite Industries",sector:"Consumer"},
    {symbol:"HAVELLS",name:"Havells India",sector:"Consumer"},
    {symbol:"DABUR",name:"Dabur India",sector:"FMCG"},
    {symbol:"MARICO",name:"Marico",sector:"FMCG"},
    {symbol:"COLPAL",name:"Colgate-Palmolive India",sector:"FMCG"},
    {symbol:"BRITANNIA",name:"Britannia Industries",sector:"FMCG"},
    {symbol:"PNB",name:"Punjab National Bank",sector:"Banking"},
    {symbol:"BANKBARODA",name:"Bank of Baroda",sector:"Banking"},
    {symbol:"CANBK",name:"Canara Bank",sector:"Banking"},
    {symbol:"IDFCFIRSTB",name:"IDFC First Bank",sector:"Banking"},
    {symbol:"YESBANK",name:"Yes Bank",sector:"Banking"},
    {symbol:"FEDERALBNK",name:"Federal Bank",sector:"Banking"},
    {symbol:"INDUSINDBK",name:"IndusInd Bank",sector:"Banking"},
    {symbol:"TECHM",name:"Tech Mahindra",sector:"IT"},
    {symbol:"MPHASIS",name:"Mphasis",sector:"IT"},
    {symbol:"LTIM",name:"LTIMindtree",sector:"IT"},
    {symbol:"PERSISTENT",name:"Persistent Systems",sector:"IT"},
    {symbol:"COFORGE",name:"Coforge",sector:"IT"},
    {symbol:"NAUKRI",name:"Info Edge (Naukri)",sector:"Internet"},
    {symbol:"PAYTM",name:"One 97 Communications",sector:"Fintech"},
    {symbol:"ZYDUSLIFE",name:"Zydus Lifesciences",sector:"Pharma"},
    {symbol:"LUPIN",name:"Lupin",sector:"Pharma"},
    {symbol:"AUROPHARMA",name:"Aurobindo Pharma",sector:"Pharma"},
    {symbol:"GAIL",name:"GAIL India",sector:"Energy"},
    {symbol:"BPCL",name:"Bharat Petroleum",sector:"Energy"},
    {symbol:"COALINDIA",name:"Coal India",sector:"Mining"},
    {symbol:"RECLTD",name:"REC",sector:"Finance"},
    {symbol:"PFC",name:"Power Finance Corp",sector:"Finance"},
    {symbol:"HDFCLIFE",name:"HDFC Life Insurance",sector:"Insurance"},
    {symbol:"SBILIFE",name:"SBI Life Insurance",sector:"Insurance"},
    {symbol:"ICICIGI",name:"ICICI Lombard",sector:"Insurance"},
    {symbol:"MRF",name:"MRF",sector:"Auto"},
    {symbol:"BOSCHLTD",name:"Bosch",sector:"Auto"},
    {symbol:"SIEMENS",name:"Siemens India",sector:"Industrial"},
    {symbol:"ABB",name:"ABB India",sector:"Industrial"},
    {symbol:"CUMMINSIND",name:"Cummins India",sector:"Industrial"},
    {symbol:"DIXON",name:"Dixon Technologies",sector:"Consumer"},
    {symbol:"POLYCAB",name:"Polycab India",sector:"Industrial"},
    {symbol:"GODREJPROP",name:"Godrej Properties",sector:"Real Estate"},
    {symbol:"TRENT",name:"Trent",sector:"Retail"},
    {symbol:"JUBLFOOD",name:"Jubilant FoodWorks",sector:"Consumer"},
    {symbol:"BEL",name:"Bharat Electronics",sector:"Defence"},
    {symbol:"TATAELXSI",name:"Tata Elxsi",sector:"IT"},
    {symbol:"CDSL",name:"CDSL",sector:"Finance"},
    {symbol:"ADANIGREEN",name:"Adani Green Energy",sector:"Utilities"},
    {symbol:"ADANIPOWER",name:"Adani Power",sector:"Utilities"},
    {symbol:"JSWSTEEL",name:"JSW Steel",sector:"Metals"},
    {symbol:"SAIL",name:"Steel Authority of India",sector:"Metals"},
    {symbol:"JINDALSTEL",name:"Jindal Steel & Power",sector:"Metals"},
    {symbol:"GODREJCP",name:"Godrej Consumer Products",sector:"FMCG"},
    {symbol:"PAGEIND",name:"Page Industries",sector:"Retail"},
    {symbol:"SRF",name:"SRF",sector:"Chemicals"},
  ];
  res.json(stocks);
};
