const STOCKS = [
  { symbol: 'NIFTY', name: 'Nifty 50 Index', sector: 'Index', yahoo: '^NSEI' },
  { symbol: 'BANKNIFTY', name: 'Bank Nifty Index', sector: 'Index', yahoo: '^NSEBANK' },
  { symbol: 'FINNIFTY', name: 'Nifty Financial Services', sector: 'Index', yahoo: '^CNXFIN' },
  { symbol: 'MIDCPNIFTY', name: 'Nifty Midcap Select', sector: 'Index', yahoo: '^NSEMDCP50' },
  { symbol: 'NIFTYBEES', name: 'Nippon India ETF Nifty BeES', sector: 'ETF' },
  { symbol: 'BANKBEES', name: 'Nippon India ETF Bank BeES', sector: 'ETF' },
  { symbol: 'JUNIORBEES', name: 'Nippon India ETF Junior BeES', sector: 'ETF' },
  { symbol: 'GOLDBEES', name: 'Nippon India ETF Gold BeES', sector: 'ETF' },
  { symbol: 'RELIANCE', name: 'Reliance Industries', sector: 'Energy' },
  { symbol: 'TCS', name: 'Tata Consultancy Services', sector: 'IT' },
  { symbol: 'HDFCBANK', name: 'HDFC Bank', sector: 'Banking' },
  { symbol: 'INFY', name: 'Infosys', sector: 'IT' },
  { symbol: 'ICICIBANK', name: 'ICICI Bank', sector: 'Banking' },
  { symbol: 'HINDUNILVR', name: 'Hindustan Unilever', sector: 'FMCG' },
  { symbol: 'SBIN', name: 'State Bank of India', sector: 'Banking' },
  { symbol: 'BHARTIARTL', name: 'Bharti Airtel', sector: 'Telecom' },
  { symbol: 'ITC', name: 'ITC', sector: 'FMCG' },
  { symbol: 'LT', name: 'Larsen & Toubro', sector: 'Infra' },
  { symbol: 'KOTAKBANK', name: 'Kotak Mahindra Bank', sector: 'Banking' },
  { symbol: 'AXISBANK', name: 'Axis Bank', sector: 'Banking' },
  { symbol: 'ASIANPAINT', name: 'Asian Paints', sector: 'Consumer' },
  { symbol: 'MARUTI', name: 'Maruti Suzuki', sector: 'Auto' },
  { symbol: 'SUNPHARMA', name: 'Sun Pharmaceutical', sector: 'Pharma' },
  { symbol: 'TITAN', name: 'Titan Company', sector: 'Consumer' },
  { symbol: 'ULTRACEMCO', name: 'UltraTech Cement', sector: 'Cement' },
  { symbol: 'BAJFINANCE', name: 'Bajaj Finance', sector: 'Finance' },
  { symbol: 'BAJAJFINSV', name: 'Bajaj Finserv', sector: 'Finance' },
  { symbol: 'NESTLEIND', name: 'Nestle India', sector: 'FMCG' },
  { symbol: 'WIPRO', name: 'Wipro', sector: 'IT' },
  { symbol: 'TECHM', name: 'Tech Mahindra', sector: 'IT' },
  { symbol: 'HCLTECH', name: 'HCL Technologies', sector: 'IT' },
  { symbol: 'TATAMOTORS', name: 'Tata Motors', sector: 'Auto' },
  { symbol: 'M&M', name: 'Mahindra & Mahindra', sector: 'Auto' },
  { symbol: 'TATASTEEL', name: 'Tata Steel', sector: 'Metals' },
  { symbol: 'JSWSTEEL', name: 'JSW Steel', sector: 'Metals' },
  { symbol: 'POWERGRID', name: 'Power Grid Corporation', sector: 'Utilities' },
  { symbol: 'NTPC', name: 'NTPC', sector: 'Utilities' },
  { symbol: 'ONGC', name: 'Oil & Natural Gas Corp', sector: 'Energy' },
  { symbol: 'COALINDIA', name: 'Coal India', sector: 'Mining' },
  { symbol: 'ADANIPORTS', name: 'Adani Ports', sector: 'Logistics' },
  { symbol: 'ADANIENT', name: 'Adani Enterprises', sector: 'Conglomerate' },
  { symbol: 'ADANIGREEN', name: 'Adani Green', sector: 'Utilities' },
  { symbol: 'ADANIPOWER', name: 'Adani Power', sector: 'Utilities' },
  { symbol: 'GRASIM', name: 'Grasim Industries', sector: 'Materials' },
  { symbol: 'SHRIRAMFIN', name: 'Shriram Finance', sector: 'Finance' },
  { symbol: 'DRREDDY', name: 'Dr. Reddy Laboratories', sector: 'Pharma' },
  { symbol: 'CIPLA', name: 'Cipla', sector: 'Pharma' },
  { symbol: 'DIVISLAB', name: 'Divis Laboratories', sector: 'Pharma' },
  { symbol: 'APOLLOHOSP', name: 'Apollo Hospitals', sector: 'Healthcare' },
  { symbol: 'TATACONSUM', name: 'Tata Consumer Products', sector: 'FMCG' },
  { symbol: 'BRITANNIA', name: 'Britannia', sector: 'FMCG' },
  { symbol: 'EICHERMOT', name: 'Eicher Motors', sector: 'Auto' },
  { symbol: 'HEROMOTOCO', name: 'Hero MotoCorp', sector: 'Auto' },
  { symbol: 'BAJAJ-AUTO', name: 'Bajaj Auto', sector: 'Auto' },
  { symbol: 'HINDALCO', name: 'Hindalco Industries', sector: 'Metals' },
  { symbol: 'INDUSINDBK', name: 'IndusInd Bank', sector: 'Banking' },
  { symbol: 'SBILIFE', name: 'SBI Life', sector: 'Insurance' },
  { symbol: 'HDFCLIFE', name: 'HDFC Life', sector: 'Insurance' },
  { symbol: 'LTIM', name: 'LTIMindtree', sector: 'IT' },
  { symbol: 'PERSISTENT', name: 'Persistent Systems', sector: 'IT' },
  { symbol: 'SIEMENS', name: 'Siemens India', sector: 'Industrial' },
  { symbol: 'ABB', name: 'ABB India', sector: 'Industrial' },
  { symbol: 'BEL', name: 'Bharat Electronics', sector: 'Defence' },
  { symbol: 'HAL', name: 'Hindustan Aeronautics', sector: 'Defence' },
  { symbol: 'DLF', name: 'DLF', sector: 'Real Estate' },
  { symbol: 'LODHA', name: 'Macrotech Developers', sector: 'Real Estate' },
  { symbol: 'GODREJPROP', name: 'Godrej Properties', sector: 'Real Estate' },
  { symbol: 'RECLTD', name: 'REC', sector: 'Finance' },
  { symbol: 'PFC', name: 'Power Finance Corp', sector: 'Finance' },
  { symbol: 'BANKBARODA', name: 'Bank of Baroda', sector: 'Banking' },
  { symbol: 'PNB', name: 'Punjab National Bank', sector: 'Banking' },
  { symbol: 'CANBK', name: 'Canara Bank', sector: 'Banking' },
  { symbol: 'FEDERALBNK', name: 'Federal Bank', sector: 'Banking' },
  { symbol: 'IDFCFIRSTB', name: 'IDFC First Bank', sector: 'Banking' },
  { symbol: 'YESBANK', name: 'Yes Bank', sector: 'Banking' },
  { symbol: 'JIOFIN', name: 'Jio Financial Services', sector: 'Finance' },
  { symbol: 'CHOLAFIN', name: 'Cholamandalam Investment', sector: 'Finance' },
  { symbol: 'MUTHOOTFIN', name: 'Muthoot Finance', sector: 'Finance' },
  { symbol: 'TATAPOWER', name: 'Tata Power', sector: 'Utilities' },
  { symbol: 'GAIL', name: 'GAIL India', sector: 'Energy' },
  { symbol: 'BPCL', name: 'Bharat Petroleum', sector: 'Energy' },
  { symbol: 'IOC', name: 'Indian Oil Corporation', sector: 'Energy' },
  { symbol: 'OIL', name: 'Oil India', sector: 'Energy' },
  { symbol: 'VEDL', name: 'Vedanta', sector: 'Metals' },
  { symbol: 'SAIL', name: 'SAIL', sector: 'Metals' },
  { symbol: 'HAVELLS', name: 'Havells India', sector: 'Consumer' },
  { symbol: 'DIXON', name: 'Dixon Technologies', sector: 'Consumer' },
  { symbol: 'POLYCAB', name: 'Polycab', sector: 'Industrial' },
  { symbol: 'PIDILITIND', name: 'Pidilite Industries', sector: 'Consumer' },
  { symbol: 'DMART', name: 'Avenue Supermarts', sector: 'Retail' },
  { symbol: 'TRENT', name: 'Trent', sector: 'Retail' },
  { symbol: 'ZOMATO', name: 'Zomato', sector: 'Internet' },
  { symbol: 'SWIGGY', name: 'Swiggy', sector: 'Internet' },
  { symbol: 'NAUKRI', name: 'Info Edge', sector: 'Internet' },
  { symbol: 'PAYTM', name: 'Paytm', sector: 'Fintech' },
  { symbol: 'IRCTC', name: 'IRCTC', sector: 'Travel' },
  { symbol: 'INDIGO', name: 'InterGlobe Aviation', sector: 'Travel', yahoo: 'INDIGO.NS' },
  { symbol: 'MOTHERSON', name: 'Samvardhana Motherson', sector: 'Auto Ancillary', yahoo: 'MOTHERSON.NS' },
  { symbol: 'TVSMOTOR', name: 'TVS Motor Company', sector: 'Auto' },
  { symbol: 'AUROPHARMA', name: 'Aurobindo Pharma', sector: 'Pharma' },
  { symbol: 'ZYDUSLIFE', name: 'Zydus Lifesciences', sector: 'Pharma' },
  { symbol: 'LUPIN', name: 'Lupin', sector: 'Pharma' },
  { symbol: 'TORNTPHARM', name: 'Torrent Pharmaceuticals', sector: 'Pharma' },
  { symbol: 'MANKIND', name: 'Mankind Pharma', sector: 'Pharma' },
  { symbol: 'MAXHEALTH', name: 'Max Healthcare', sector: 'Healthcare' },
  { symbol: 'MARICO', name: 'Marico', sector: 'FMCG' },
  { symbol: 'DABUR', name: 'Dabur India', sector: 'FMCG' },
  { symbol: 'COLPAL', name: 'Colgate-Palmolive India', sector: 'FMCG' },
  { symbol: 'GODREJCP', name: 'Godrej Consumer', sector: 'FMCG' },
  { symbol: 'AMBUJACEM', name: 'Ambuja Cements', sector: 'Cement' },
  { symbol: 'ACC', name: 'ACC', sector: 'Cement' },
  { symbol: 'BSE', name: 'BSE', sector: 'Exchange' },
  { symbol: 'MCX', name: 'Multi Commodity Exchange', sector: 'Exchange' },
  { symbol: 'CGPOWER', name: 'CG Power', sector: 'Industrial' },
  { symbol: 'NHPC', name: 'NHPC', sector: 'Utilities' },
  { symbol: 'LICI', name: 'Life Insurance Corporation', sector: 'Insurance' },
  { symbol: 'MRF', name: 'MRF', sector: 'Auto' }
];

const QUOTE_SYMBOLS = Object.fromEntries(
  STOCKS.map(stock => [stock.symbol, stock.yahoo || `${stock.symbol}.NS`])
);

function getStocks() {
  return STOCKS.map(({ yahoo, ...stock }) => stock);
}

module.exports = {
  QUOTE_SYMBOLS,
  STOCKS,
  getStocks,
};